emm_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: EMMUserBundle:Default:index }
    
emm_user_index:
    path:   /user/index
    defaults:   { _controller: EMMUserBundle:User:index }

emm_user_article:
    path:   /user/article/{page}
    defaults:   { _controller: EMMUserBundle:User:article , page: 0 }
    requirements: 
        page: \d+
    